---
- name: Configure CentOS EC2 instances
  hosts: n1
  become: yes
  vars:
    app_directory: /home/centos/ansible-flask
    git_repo_url: https://github.com/reniade314/flask-project.git

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Create ansible-flask directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'
      become_user: centos

    - name: Clone GitHub repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"
      become_user: centos

    - name: Update repositories and install Python
      yum:
        name: python3
        state: present

    - name: Install pip (Python package manager)
      yum:
        name: python3-pip
        state: present

    - name: Install virtualenv package
      pip:
        name: virtualenv
        executable: pip3
        state: present

    - name: Create a virtual environment
      command: virtualenv -p python3 venv
      args:
        chdir: "{{ app_directory }}/repository"
      become_user: centos

    - name: Activate the virtual environment
      shell:
       cmd: "source {{ app_directory }}/repository/venv/bin/activate && python --version"
      become_user: centos


    - name: Install Flask within the virtual environment
      pip:
        name: flask
        executable: pip3
        state: present

    - name: Run Flask app
      command: nohup python3 app.py &
      args:
        chdir: "{{ app_directory }}/repository"
      become_user: centos

...