---
- name: Configure CentOS EC2 instances
  hosts: n1
  become: yes
  vars:
    app_directory: /home/centos/ansible-flask
    git_repo_url: https://github.com/reniade314/flask-project.git

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Clone GitHub repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_directory }}/repository"
      become_user: centos

    - name: Update repositories and install Python
      yum:
        name: python3
        state: present

    - name: Install pip (Python package manager)
      yum:
        name: python3-pip
        state: present

    - name: Install virtualenv package
      pip:
        name: virtualenv
        executable: pip3
        state: present

    - name: Create a virtual environment
      command: virtualenv -p python3 venv
      args:
        chdir: "{{ app_directory }}/repository"
      become_user: centos

    - name: Activate the virtual environment
      command: source {{ app_directory }}/repository/venv/bin/activate
      become_user: centos

    - name: Install Flask within the virtual environment
      pip:
        name: flask
        executable: pip3
        state: present

    - name: Deactivate the virtual environment
      command: deactivate
      become_user: centos

    - name: Copy Flask app code to servers
      synchronize:
        src: "{{ app_directory }}/repository"
        dest: "{{ app_directory }}"
        delete: yes
      become_user: centos

    - name: Run Flask app
      command: nohup python3 flask.py &
      args:
        chdir: "{{ app_directory }}/repository"
      become_user: centos

...